//The path Module provides utillities for working with file directory paths.
const path = require('path')

// console.log(path.dirname("c:/Users/prashant/Videos/Node js/starting of Node/")) returns the absolute path of file 

// console.log(path.extname('C:/Users/prashant/Downloads/Node js notes/practice codes/#5  Path_module_in_node.js')) reutrn the extension of the file

// console.log(path.basename('C:/Users/prashant/Downloads/Node js notes/practice codes/#5  Path_module_in_node.js')) return the name of file with extension

// console.log(path.parse('C:/Users/prashant/Downloads/Node js notes/practice codes/#5  Path_module_in_node.js'))  return json which contain root ,dir ,basename ,extension and name



