// creating own modules

// For importing the modules
// const m = require('./FILe_name') 
// const {property1,property2} = require("file_name)") this is for only two propertys respectivly

const add = (a,b)=>{
    return a+b;
}

const name = 'prashant'; 


// For exporting this moduls
// module.exports = add; this is for single variable and function

// module.exports.add = add

// module.exports.name = name
// this is for exporting multiple function and variables

// module.exports = {add,name}; export also take and object of propertyes name

