/*
npm is a package manager for the JavaScript programming language
it is the default package manager for the javascript runtime 
envitonment node.js
*/

// How to include npm packages in our projectes

// step 1
// run command 'npm init' in the root folder
// this will create package.json

// step 2
// then import that module

const chalk = require('chalk')

console.log(chalk.green.inverse('sccess'))




